language: rust
notifications:
  irc: "irc.mozilla.org#hematite"
script:
  - rustup component add rustfmt
  - cargo fmt -- --check
  - cargo test -v
  - cargo doc -v
after_success:
  - curl http://docs.piston.rs/travis-doc-upload.sh | sh
